const USER_OR_PASSWORD_NOT_EXISTS = 'USER_OR_PASSWORD_NOT_EXISTS'
const USER_HAS_ALREADY = 'USER_HAS_ALREADY'
const USER_IS_NOT_EXISTS = 'USER_IS_NOT_EXISTS'
const PASSWORD_IS_NOT_CORRECT = 'PASSWORD_IS_NOT_CORRECT'
const AUTHORIZATION_IS_NOT_INVALID = 'AUTHORIZATION_IS_NOT_INVALID'
const NOT_PERMISSION = 'NOT_PERMISSION'
const FORBIDDEN = 'FORBIDDEN'
const METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED'

module.exports = {
 USER_OR_PASSWORD_NOT_EXISTS,
 USER_HAS_ALREADY,
 USER_IS_NOT_EXISTS,
 PASSWORD_IS_NOT_CORRECT,
 AUTHORIZATION_IS_NOT_INVALID,
 NOT_PERMISSION,
 FORBIDDEN,
 METHOD_NOT_ALLOWED
}