export const GET_RECOMMEND_LIST = 'GET_RECOMMEND_LIST';

export const GET_POPULAR_LIST = 'GET_POPULAR_LIST';

export const GET_QUESTION_LIST = 'GET_QUESTION_LIST';

export const GET_INVITE_LIST = 'GET_INVITE_LIST';
